name: Workflow

on: [push, workflow_dispatch]

jobs:
  build-win:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - name: Generate Project files
        run: scripts/GenerateWindowsProjects.bat
        
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
        
      - name: Build
        run: msbuild /m /p:Configuration=${{matrix.configuration}} .
        
      - name: Upload test artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.configuration}}-YART-Test
          path: ./bin/${{matrix.configuration}}-windows/YART-Test/YART-Test.exe
      
  test-win:
    needs: build-win
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
      - name: Download test artifact
        uses: actions/download-artifact@v2.0.9
        with:
          name: ${{matrix.configuration}}-YART-Test
      
      - name: show files
        run: dir

      - name: Run Tests
        run: .\YART-Test.exe
