name: CI

on: [push, workflow_dispatch]

jobs:
  build-win:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - name: Generate Project files
        run: scripts/GenerateWindowsProjects.bat
        
      - name: Build
        run: cmake --build build --config ${{matrix.configuration}}
        
      - name: Upload test artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows-${{matrix.configuration}}-YART-Test
          path: ./build/YART-Test/${{matrix.configuration}}/YART-Test.exe
      
  test-win:
    needs: build-win
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
      - name: Download test artifact
        uses: actions/download-artifact@v2.0.9
        with:
          name: windows-${{matrix.configuration}}-YART-Test
      
      - name: show files
        run: dir

      - name: Run Tests
        run: .\YART-Test.exe
  
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - name: Generate Project files
        run: scripts/GenerateLinuxProjects.sh
        
      - name: Build
        run: cmake --build build/${{matrix.configuration}}
        
      - name: Upload test artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux-${{matrix.configuration}}-YART-Test
          path: ./build/${{matrix.configuration}}/YART-Test/YART-Test

  test-linux:
    needs: build-linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
        
    steps:
      - name: Download test artifact
        uses: actions/download-artifact@v2.0.9
        with:
          name: linux-${{matrix.configuration}}-YART-Test

      - run: ls -laR .

      - name: Make test executable
        run: chmod +x YART-Test

      - name: Run Tests
        run: ./YART-Test